name: yando
description: A new ToDo App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.4
  logger: ^1.4.0
  provider: ^6.0.5
  flutter_launcher_icons: ^0.13.1
  dio: ^5.2.1+1
  flutter_dotenv: ^5.1.0
  intl: ^0.17.0
  hive: ^2.2.3
  device_info_plus: ^9.0.2
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  flutter_flavor: ^3.1.1
  firebase_remote_config: ^4.2.3
  firebase_analytics: ^10.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/yando_icon.png'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env