// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM_y_KtHGkMZltsEUtLm67OjQSXs9bLgg',
    appId: '1:159249535918:web:38b00f8ea64b771854ee3f',
    messagingSenderId: '159249535918',
    projectId: 'yandofirebaseapp',
    authDomain: 'yandofirebaseapp.firebaseapp.com',
    storageBucket: 'yandofirebaseapp.appspot.com',
    measurementId: 'G-9E44XYRBRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3IOGW3SACwLAovtuO5aPrH6Y4iIdSBVI',
    appId: '1:159249535918:android:89a3c1a877ccce4a54ee3f',
    messagingSenderId: '159249535918',
    projectId: 'yandofirebaseapp',
    storageBucket: 'yandofirebaseapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtLwVSXKuwx-hWWSalFKwkRAL7MryfSvo',
    appId: '1:159249535918:ios:5f0dcbc1352497c654ee3f',
    messagingSenderId: '159249535918',
    projectId: 'yandofirebaseapp',
    storageBucket: 'yandofirebaseapp.appspot.com',
    iosClientId:
        '159249535918-behe6r2ccg2fnlgqn9uj1aj818pa8bfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.yando',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtLwVSXKuwx-hWWSalFKwkRAL7MryfSvo',
    appId: '1:159249535918:ios:5f0dcbc1352497c654ee3f',
    messagingSenderId: '159249535918',
    projectId: 'yandofirebaseapp',
    storageBucket: 'yandofirebaseapp.appspot.com',
    iosClientId:
        '159249535918-behe6r2ccg2fnlgqn9uj1aj818pa8bfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.yando',
  );
}
