name: Test

on:
  push:
    branches:
      - main
      - '*'

  pull_request:
    branches:
      - main

jobs:
  analyze:
    timeout-minutes: 10
    name: 'Analyze'
    runs-on: ubuntu-latest
    steps:
      - run: dart format
      - run: dart pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
